### ISSUE TITLE
Miscounting the number of remaining lessons 

### ISSUE THREAD

**Issue by szaszlyki21** [Ogaku/Oshi#11]
Maybe intended, if the last lessons are the same(j. Polski, j. Polski ) the app counts them as one lesson ![IMG_2531](https://github.com/Ogaku/Oshi/assets/96011540/b9658620-99de-404c-a31f-90b5d0c3a690)
![IMG_2532](https://github.com/Ogaku/Oshi/assets/96011540/1bb56fbc-1362-4930-8190-86ba2e2372bd)

**Comment by meruune** [comment]
The 'later' part refers to the number of lessons remaining after the 'next (up)' lesson. I understand that this may seem unclear and may require a rework.

> Next up — "następnie"
> Later — "później" (exclusive względem "następnie")

Also:

- [x] Don't use placeholder values for classrooms, display just the lesson/subject name

**Comment by szaszlyki21** [comment]
Oh, okay that makes sense.
